services:
  - type: web
    name: skytravel
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "pon-una-clave-secreta-aqui"
      - key: ALLOWED_HOSTS
        value: "skytravel-1pfj.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: skytravel_db
          property: connectionString
