# Generated by Django 5.2.1 on 2025-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_asientos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
